import type { Employee } from "./types";

export const employeeData: Employee[] = [
  {
    key: "1",
    employeeId: "EMP001",
    firstName: "John",
    lastName: "Smith",
    email: "john@example.com",
    phone: "9876543210",
    department: "IT",
    designation: "Software Engineer",
    joiningDate: "12 Jun 2026",
    salary: 65000,
    status: "Active",
  },
  {
    key: "2",
    employeeId: "EMP002",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah@example.com",
    phone: "9876543211",
    department: "HR",
    designation: "HR Manager",
    joiningDate: "15 Apr 2026",
    salary: 70000,
    status: "On Leave",
  },
  {
    key: "3",
    employeeId: "EMP003",
    firstName: "David",
    lastName: "Lee",
    email: "david@example.com",
    phone: "9876543212",
    department: "Finance",
    designation: "Accountant",
    joiningDate: "10 Jan 2026",
    salary: 60000,
    status: "Inactive",
  },
  {
    key: "4",
    employeeId: "EMP004",
    firstName: "Emily",
    lastName: "Brown",
    email: "emily@example.com",
    phone: "9876543213",
    department: "Sales",
    designation: "Sales Executive",
    joiningDate: "08 Feb 2026",
    salary: 52000,
    status: "Active",
  },
  {
    key: "5",
    employeeId: "EMP005",
    firstName: "Robert",
    lastName: "Wilson",
    email: "robert@example.com",
    phone: "9876543214",
    department: "IT",
    designation: "Tech Lead",
    joiningDate: "20 Mar 2026",
    salary: 90000,
    status: "Active",
  },
  {
    key: "6",
    employeeId: "EMP006",
    firstName: "Sophia",
    lastName: "Taylor",
    email: "sophia@example.com",
    phone: "9876543215",
    department: "Admin",
    designation: "Administrator",
    joiningDate: "25 May 2026",
    salary: 48000,
    status: "Active",
  },
];
